In [3]:
x = range(10)

In [6]:
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
type(x)

list

In [11]:
import numpy as np
y = np.arange(10)

In [12]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
type(y)

numpy.ndarray

In [32]:
z = np.array([[1,2,3],[2,3,4]])

In [29]:
z

array([[1, 2, 3],
       [2, 3, 4]])

In [42]:
g = np.array([np.arange(5),np.arange(1,6)])

In [43]:
g

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5]])

In [47]:
import pandas as pd
s = pd.Series(np.array([1,2,3]),index = ['a','b','c'])
s

a    1
b    2
c    3
dtype: int64

In [73]:
from pandas import Series, DataFrame
from numpy import array, arange
a = array([[1,2],[3,4]])
df = DataFrame(a)
print df

   0  1
0  1  2
1  3  4


In [68]:
df.columns = ['Cai','Chen']
df.index = ['a','b']
print df

   Cai  Chen
a    1     2
b    3     4


In [69]:
df2 = DataFrame(array([[1,2],[3,4]]), columns=['Cai','Chen'], index=['a','b'])
print df2

   Cai  Chen
a    1     2
b    3     4


In [74]:
s1 = Series(arange(5))
s2 = Series(arange(1,6))
df3 = DataFrame({'Cai':s1,'Chen':s2})
print df3

   Cai  Chen
0    0     1
1    1     2
2    2     3
3    3     4
4    4     5


In [82]:
df3['Rong'] = s1
print df3

   Cai  Chen  Rong
0    0     1     0
1    2     2     1
2    4     3     2
3    6     4     3
4    8     5     4


In [90]:
df3['Cai'] = df3['Cai'] / 13
print df3

        Cai  Chen  Rong
0  0.000000     1     0
1  0.757396     2     1
2  1.514793     3     2
3  2.272189     4     3
4  3.029586     5     4


In [99]:
summ = df3['Cai'].describe()
len = summ['count']
print len

5.0


In [ ]:
mean = 